### PR TITLE
Correction of bug #150

### LINKED ISSUE #150: ClassCastException (ModuleDeclaration cannot be cast to PHPModuleDeclaration)
Hi,
recently I've got following exception:

eclipse.buildId=4.6.2.M20161124-1400
java.version=1.8.0_66
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86, WS=win32, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86 -product org.eclipse.epp.package.jee.product

org.pdtextensions.semanticanalysis
Error
Wed Jan 18 14:55:28 CET 2017
Exception during validation

java.lang.ClassCastException: org.eclipse.dltk.ast.declarations.ModuleDeclaration cannot be cast to org.eclipse.php.internal.core.compiler.ast.nodes.PHPModuleDeclaration
	at org.pdtextensions.semanticanalysis.validation.validator.VariableValidator.validate(VariableValidator.java:242)
	at org.pdtextensions.internal.semanticanalysis.integration.BuildParticipant.validate(BuildParticipant.java:102)
	at org.pdtextensions.internal.semanticanalysis.integration.BuildParticipant.build(BuildParticipant.java:72)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.run(ReconcileBuilder.java:108)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.dltk.internal.core.ReconcileBuilder.build(ReconcileBuilder.java:85)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:90)
	at org.eclipse.dltk.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:57)
	at org.eclipse.dltk.internal.core.ModelOperation.run(ModelOperation.java:703)
	at org.eclipse.dltk.internal.core.ModelOperation.runOperation(ModelOperation.java:769)
	at org.eclipse.dltk.internal.core.SourceModule.reconcile(SourceModule.java:298)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.reconcile(PhpReconcilingStrategy.java:148)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.access$0(PhpReconcilingStrategy.java:136)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy$2.run(PhpReconcilingStrategy.java:211)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.validate(PhpReconcilingStrategy.java:209)
	at org.eclipse.php.internal.ui.editor.validation.PhpReconcilingStrategy.validate(PhpReconcilingStrategy.java:187)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.validate(ReconcileStepForValidator.java:250)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.reconcileModel(ReconcileStepForValidator.java:208)
	at org.eclipse.jface.text.reconciler.AbstractReconcileStep.reconcile(AbstractReconcileStep.java:89)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ValidatorStrategy.reconcile(ValidatorStrategy.java:269)
	at org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor.process(DocumentRegionProcessor.java:321)
	at org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor.process(StructuredRegionProcessor.java:258)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:691)

### PR DESCRIPTION
**Pull request by tbl0605**

### CODE REVIEW

File: org.pdtextensions.semanticanalysis/src/org/pdtextensions/semanticanalysis/validation/validator/VariableValidator.java [hunk 1]
```diff
@@ -261,7 +263,7 @@ public int compare(VarComment o1, VarComment o2) {
 
 			@Override
 			public int compare(PHPDocBlock o1, PHPDocBlock o2) {
-				return o1.sourceStart() - o1.sourceStart();
```
Comment (tbl0605) [inline org.pdtextensions.semanticanalysis/src/org/pdtextensions/semanticanalysis/validation/validator/VariableValidator.java]: This was probably the initial intention (@Dawid you should confirm this please).

Comment (zulus) [inline org.pdtextensions.semanticanalysis/src/org/pdtextensions/semanticanalysis/validation/validator/VariableValidator.java]: right

**Comment by zulus** [comment]
Thanks!
